# Generated by Django 4.2.16 on 2024-10-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentif', '0004_user_id_42_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
