# Generated by Django 4.2.16 on 2024-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentif', '0005_user_two_factor_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
