# Generated by Django 4.2.16 on 2024-11-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentif', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=16, unique=True),
        ),
    ]
