# Generated by Django 4.2.16 on 2024-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('city', models.CharField(blank=True, default='Málaga', max_length=100)),
                ('country', models.CharField(blank=True, default='Spain', max_length=100)),
                ('played_games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('defeats', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/')),
                ('friends', models.ManyToManyField(blank=True, to='profileapi.profile')),
            ],
        ),
    ]
