# Generated by Django 4.2.16 on 2024-10-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0003_remove_profile_username_profile_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
