# Generated by Django 4.2.16 on 2024-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0004_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.png', null=True, upload_to='media/avatars/'),
        ),
    ]
