# Generated by Django 4.2.16 on 2024-10-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0004_profile_preferred_language'),
        ('profileapi', '0005_profile_avatar'),
    ]

    operations = [
    ]
