# Generated by Django 4.2.16 on 2024-10-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
