# Generated by Django 4.2.16 on 2024-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0009_rename_receiver_id_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='unread', max_length=16),
        ),
    ]
