# Generated by Django 4.2.16 on 2024-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0010_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='profileapi.profile'),
        ),
    ]
