# Generated by Django 4.2.16 on 2024-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0011_profile_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='game',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
