# Generated by Django 4.2.16 on 2024-11-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0012_notification_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='game',
            new_name='game_type',
        ),
    ]
