# Generated by Django 4.2.16 on 2024-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0014_alter_notification_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=22),
        ),
    ]
