# Generated by Django 4.2.16 on 2024-11-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0016_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='defeats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='played_games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wins',
        ),
    ]
