# Generated by Django 4.2.16 on 2024-10-01 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='game_round',
            field=models.CharField(choices=[('single', 'single'), ('semifinal1', 'Semi-Final 1'), ('semifinal2', 'Semi-Final 2'), ('final', 'Final')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('pong', 'Pong')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_games', to='play.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_games', to='play.player'),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
