# Generated by Django 4.2.16 on 2024-10-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_rename_score_player1_game_p1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_id', models.IntegerField(blank=True, null=True)),
                ('p1_name', models.CharField(max_length=16)),
                ('p2_id', models.IntegerField(blank=True, null=True)),
                ('p2_name', models.CharField(max_length=16)),
                ('p3_id', models.IntegerField(blank=True, null=True)),
                ('p3_name', models.CharField(max_length=16)),
                ('p4_id', models.IntegerField(blank=True, null=True)),
                ('p4_name', models.CharField(max_length=16)),
                ('winner_id', models.IntegerField(blank=True, null=True)),
                ('winner_name', models.CharField(blank=True, max_length=16, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_final', to='play.game')),
                ('semifinal1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_semifinal1', to='play.game')),
                ('semifinal2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_semifinal2', to='play.game')),
            ],
        ),
    ]
