# Generated by Django 4.2.16 on 2024-10-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('pong', 'Pong')], default='Pong', max_length=16),
            preserve_default=False,
        ),
    ]
