# Generated by Django 4.2.16 on 2024-10-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_tournament_tournament_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='p1_name',
            new_name='tp1_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='p2_name',
            new_name='tp2_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='p3_name',
            new_name='tp3_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='p4_name',
            new_name='tp4_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='p1_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='p2_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='p3_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='p4_id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tp1_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tp2_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tp3_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tp4_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='p1_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='p2_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
