# Generated by Django 4.2.16 on 2024-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_rename_p1_name_tournament_tp1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('pong', 'pong')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('pong', 'pong')], max_length=16),
        ),
    ]
