# Generated by Django 4.2.16 on 2024-10-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_alter_game_game_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tp1_id',
            new_name='t_p1_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp1_name',
            new_name='t_p1_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp2_id',
            new_name='t_p2_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp2_name',
            new_name='t_p2_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp3_id',
            new_name='t_p3_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp3_name',
            new_name='t_p3_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp4_id',
            new_name='t_p4_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tp4_name',
            new_name='t_p4_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='winner_id',
            new_name='t_winner_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='winner_name',
            new_name='t_winner_name',
        ),
    ]
