# Generated by Django 4.2.16 on 2024-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_rename_tp1_id_tournament_t_p1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('pong', 'pong'), ('cows', 'cows')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('pong', 'pong'), ('cows', 'cows')], max_length=16),
        ),
    ]
