# Generated by Django 4.2.16 on 2024-10-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_alter_game_game_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_type',
            new_name='game_type',
        ),
    ]
