# Generated by Django 4.2.16 on 2024-10-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0003_rename_dest_user_message_receiver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='dest_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='send_user',
        ),
    ]
